server:
  port: 8092

spring:
  application:
    name: property-view-service
  datasource:
    url: jdbc:h2:mem:property_view_service_db
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  h2:
    console:
      enabled: true

springdoc:
  swagger-ui:
    path: /property-view/swagger-ui/index.html
    url: /property-view/api-docs
  api-docs:
    path: /property-view/api-docs
